# Generated by Django 4.2.8 on 2023-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=700),
        ),
    ]
