# Generated by Django 4.2.8 on 2023-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_ingredients_alter_post_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
