# Generated by Django 3.2.23 on 2023-11-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
    ]
